# packages in environment at /software/miniconda3/envs/nipype-dev:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10           py36h174008c_0  
apipkg                    1.4                      pypi_0    pypi
appnope                   0.1.0            py36hf537a9a_0  
asn1crypto                0.24.0                   py36_0  
attrs                     17.4.0                   py36_0  
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    2.1.3                    py36_0  
bokeh                     0.13.0                   py36_0  
bz2file                   0.98                     pypi_0    pypi
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
cffi                      1.11.5           py36h342bebf_0  
chardet                   3.0.4            py36h96c241c_1  
click                     6.7              py36hec950be_0  
cloudpickle               0.5.6                    py36_0  
configparser              3.5.0                    pypi_0    pypi
cryptography              2.5              py36ha12b0ac_0  
cytoolz                   0.9.0.1          py36h1de35cc_1  
dask                      0.19.3                   py36_0  
dask-core                 0.19.3                   py36_0  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py36_0  
dipy                      0.16.0                   pypi_0    pypi
distributed               1.23.3                   py36_0  
docutils                  0.14             py36hbfde631_0  
entrypoints               0.2.3            py36hd81d71f_2  
execnet                   1.5.0                    pypi_0    pypi
expat                     2.2.5                hb8e80ba_0  
funcsigs                  1.0.2                    py36_0  
future                    0.16.0                   py36_1  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.1               h35bc53a_0  
h5py                      2.9.0                    pypi_0    pypi
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py36h8628d0a_1  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipython                   6.3.1                    py36_0  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.2.1                    py36_0  
isodate                   0.6.0                    pypi_0    pypi
jedi                      0.12.0                   py36_0  
jinja2                    2.10             py36hd36f9c5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py36hb385e00_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0  
jupyterlab                0.35.3                   py36_0  
jupyterlab_server         0.2.0                    py36_0  
keepalive                 0.5                        py_1    conda-forge
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16               h3efe00b_0  
locket                    0.2.0            py36hca03003_1  
lxml                      4.2.1                    pypi_0    pypi
markupsafe                1.0              py36h3a1e703_1  
mistune                   0.8.3            py36h1de35cc_1  
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py36h917ab60_0  
mkl_random                1.0.1            py36h78cc56f_0  
mock                      2.0.0            py36hd48142b_0  
more-itertools            4.1.0                    py36_0  
msgpack-python            0.5.6            py36h04f5b5a_1  
nbconvert                 5.3.1            py36h810822e_0  
nbformat                  4.4.0            py36h827af21_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.1                      py36_0  
neurdflib                 5.0.0.post1              pypi_0    pypi
nibabel                   2.3.3                    pypi_0    pypi
nilearn                   0.5.0                    pypi_0    pypi
nipype                    1.1.9.dev0+g5a689fc4d           dev_0    <develop>
notebook                  5.4.1                    py36_0  
numpy                     1.14.3           py36h9bb19eb_1  
numpy-base                1.14.3           py36h479e554_1  
numpydoc                  0.8.0                    py36_0  
openssl                   1.1.1b               h1de35cc_0  
packaging                 17.1                     py36_0  
pandas                    0.23.4           py36h6440ff4_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py36h3b0b094_1  
parso                     0.2.0                    py36_0  
partd                     0.3.8            py36hf5c4cb8_0  
pbr                       4.0.2                    py36_0  
pcre                      8.42                 h378b8a2_0  
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36hf512f8e_0  
pip                       9.0.3                    py36_0  
pluggy                    0.6.0            py36hb1d0581_0  
prompt_toolkit            1.0.15           py36haeda067_0  
prov                      1.5.0                    pypi_0    pypi
psutil                    5.4.7            py36h1de35cc_0  
ptyprocess                0.5.2            py36he6521c3_0  
py                        1.5.3                    py36_0  
pycparser                 2.18             py36h724b2fc_1  
pydot                     1.2.4                    py36_0  
pydotplus                 2.0.2                    py36_0  
pygments                  2.2.0            py36h240cd3f_0  
pyld                      1.0.3                    pypi_0    pypi
pyopenssl                 17.5.0           py36h51e4350_0  
pyparsing                 2.2.0            py36hb281f35_0  
pyqt                      5.9.2            py36h11d3b92_0  
pysocks                   1.6.8                    py36_0  
pytest                    3.5.0                    py36_0  
pytest-env                0.6.2                    pypi_0    pypi
pytest-forked             0.2                      pypi_0    pypi
pytest-xdist              1.22.2                   pypi_0    pypi
python                    3.6.8                haf84260_0  
python-dateutil           2.7.2                    py36_0  
pytz                      2018.4                   py36_0  
pyyaml                    3.13             py36h1de35cc_0  
pyzmq                     17.0.0           py36h1de35cc_1  
qt                        5.9.5                h02808f3_0  
qtconsole                 4.3.1            py36hd96c0ff_0  
rdflib                    4.2.2                    pypi_0    pypi
rdflib-jsonld             0.4.0                    pypi_0    pypi
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py36h4516966_1  
scikit-learn              0.20.3                   pypi_0    pypi
scipy                     1.0.1            py36hcaad992_0  
send2trash                1.5.0                    py36_0  
setuptools                39.0.1                   py36_0  
simplegeneric             0.8.1                    py36_2  
simplejson                3.14.0           py36h1de35cc_0  
sip                       4.19.8           py36h0a44026_0  
six                       1.11.0           py36h0e22d5e_1  
snowballstemmer           1.2.1            py36h6c7b616_0  
sortedcontainers          2.0.5                    py36_0  
sparqlwrapper             1.8.2                 py36_1000    conda-forge
sphinx                    1.7.3                    py36_0  
sphinxcontrib             1.0              py36h9364dc8_1  
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1  
sqlite                    3.26.0               ha441bb4_0  
tblib                     1.3.2            py36hda67792_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h625a49b_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py36_0  
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2            py36h65bd3ce_0  
traits                    4.6.0                    py36_0  
typing                    3.6.4                    py36_0  
urllib3                   1.22             py36h68b9469_0  
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1            py36h3b9701d_1  
wheel                     0.31.0                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
xlsxwriter                1.1.5                    py36_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
yapf                      0.21.0                   pypi_0    pypi
zeromq                    4.2.5                h378b8a2_0  
zict                      0.1.3                    py36_0  
zlib                      1.2.11               hf3cbc9b_2  
